//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetailProducts = new HashSet<OrderDetailProduct>();
            this.OrderDetailRooms = new HashSet<OrderDetailRoom>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> checkinDate { get; set; }
        public Nullable<System.DateTime> checkoutDate { get; set; }
        public Nullable<double> totalAmount { get; set; }
        public Nullable<int> numOfCus { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> isGroup { get; set; }
        public string note { get; set; }
        public Nullable<int> customerID { get; set; }
        public Nullable<int> staffID { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetailProduct> OrderDetailProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetailRoom> OrderDetailRooms { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
