//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.OrderDetailProducts = new HashSet<OrderDetailProduct>();
            this.OrderDetailRooms = new HashSet<OrderDetailRoom>();
        }
    
        public int id { get; set; }
        public string num { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> floorId { get; set; }
        public Nullable<int> typeRoomId { get; set; }
    
        public virtual Floor Floor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetailProduct> OrderDetailProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetailRoom> OrderDetailRooms { get; set; }
        public virtual TypeRoom TypeRoom { get; set; }
    }
}
